# Generated by Django 6.0.2 on 2026-03-02 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('comment', models.CharField(max_length=500, verbose_name='Комментарий')),
                ('country_flag', models.CharField(max_length=10, verbose_name='Флаг страны (код, напр. RU)')),
                ('number', models.CharField(max_length=20, verbose_name='Номер автомобиля')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='Installer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('photo', models.ImageField(upload_to='installers/photos/', verbose_name='Фотография')),
                ('experience_years', models.PositiveIntegerField(verbose_name='Лет опыта')),
                ('status', models.CharField(choices=[('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior')], max_length=10, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Монтажник',
                'verbose_name_plural': 'Монтажники',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название специализации')),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Специализации',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='installers/certificates/', verbose_name='Фото сертификата')),
                ('caption', models.CharField(max_length=300, verbose_name='Подпись')),
                ('installer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='core.installer', verbose_name='Монтажник')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
        migrations.CreateModel(
            name='BrigadePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Уникальная ссылка')),
                ('brigade_number', models.CharField(max_length=50, verbose_name='Номер бригады')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Рейтинг')),
                ('reviews_count', models.PositiveIntegerField(verbose_name='Количество отзывов')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.car', verbose_name='Автомобиль')),
                ('installers', models.ManyToManyField(to='core.installer', verbose_name='Монтажники')),
            ],
            options={
                'verbose_name': 'Страница бригады',
                'verbose_name_plural': 'Страницы бригад',
            },
        ),
        migrations.AddField(
            model_name='installer',
            name='projects',
            field=models.ManyToManyField(blank=True, to='core.project', verbose_name='Опыт работы (проекты)'),
        ),
        migrations.AddField(
            model_name='installer',
            name='specializations',
            field=models.ManyToManyField(blank=True, to='core.specialization', verbose_name='Специализации'),
        ),
    ]
