# Generated by Django 6.0.2 on 2026-03-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Фото автомобиля'),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Фото объекта'),
        ),
        migrations.AlterField(
            model_name='car',
            name='country_flag',
            field=models.ImageField(blank=True, null=True, upload_to='flags/', verbose_name='Флаг страны'),
        ),
    ]
